services:
  
  mongodb-estadisticas:
    image: mongo:latest
    container_name: mongodb-estadisticas
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sportboard
    ports:
      - "27018:27017"
    volumes:
      - mongodb_estadisticas_data:/data/db
    networks:
      - sportboard-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  
volumes:
  mongodb_estadisticas_data:

networks:
  sportboard-network:
    external: true