services:
  ms5-calendar:
    container_name: ms5-calendar
    build:
      context: ../../../
      dockerfile: docker/backend/ms5-calendar/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - sportboard-network
    depends_on:
      - ms5-calendar-database

  ms5-calendar-database:
    image: postgres:13
    container_name: ms5-calendar-database
    environment:
      POSTGRES_USER: calendar
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: admin
    networks:
      - sportboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calendar"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "6969:6969"



networks:
  sportboard-network:
    external: true

volumes:
  kong-db-data: