name: SportBoard-container

services:
  # Base de datos para Kong
  kong-database:
    extends:
      file: ./api-gateway/docker-compose.override.yml
      service: kong-database

  # Migraciones de Kong
  kong-migrations:
    extends:
      file: ./api-gateway/docker-compose.override.yml
      service: kong-migrations

  # API Gateway Kong
  kong:
    extends:
      file: ./api-gateway/docker-compose.override.yml
      service: kong

  # Microservicio de catálogo
  ms-catalog:
    extends:
      file: ./backend/ms-catalog/docker-compose.override.yml
      service: catalogs


  # RabbitMQ para mensajería
  rabbitmq:
    extends:
      file: ./message-broker/docker-compose.override.yml
      service: rabbitmq

networks:
  sportboard-network:
    name: sportboard-network
    driver: bridge

volumes:
  kong-db-data: