name: SportBoard-container

services:

# Microservicio de estadísticas
    mongodb-estadisticas:
        extends:
            file: ./backend/ms4-estadisticas/docker-compose.override.yml
            service: mongodb-estadisticas

    ms4-estadisticas:
        extends:
            file: ./backend/ms4-estadisticas/docker-compose.override.yml
            service: ms4-estadisticas


networks:
    sportboard-network:
        name: sportboard-network
        driver: bridge

volumes:
    mongodb_estadisticas_data:
