# Dockerfile para ms-catalog (Django)
FROM python:3.11-slim-bookworm

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8009

CMD ["python", "manage.py", "runserver", "0.0.0.0:8009"]
