version: '3.8'

services:
  competencies:
    build:
      context: ../../../backend/ms-competencies
    container_name: competencies
    ports:
      - "8010:8010"
    volumes:
      - ../../../backend/ms-competencies:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - sportboard-network

networks:
  sportboard-network:
    external: true