from dataclasses import dataclass

TOKEN_TYPE_CHOICE = (
    ("ACCOUNT_VERIFICATION", "ACCOUNT_VERIFICATION"),
    ("PASSWORD_RESET", "PASSWORD_RESET"),
)

ROLE_CHOICE = (
    ("SUPERADMIN", "SUPERADMIN"),
    ("ADMIN", "ADMIN"),
    ("COORDINATOR", "COORDINATOR"),
    ("COACH", "COACH"),
    ("ATHLETE", "ATHLETE"),
    ("ESPECTATOR", "ESPECTATOR"),
    ("REFEREE", "REFEREE"),

)

@dataclass
class TokenEnum:
    ACCOUNT_VERIFICATION = "ACCOUNT_VERIFICATION"
    PASSWORD_RESET = "PASSWORD_RESET"


@dataclass
class SystemRoleEnum:
    SUPERADMIN = "SUPERADMIN"
    ADMIN = "ADMIN"
    COORDINATOR = "COORDINATOR"
    COACH = "COACH"
    ATHLETE = "ATHLETE"
    ESPECTATOR = "ESPECTATOR"
    REEFEREE = "REFEREE"
